# Generated by Django 3.2.3 on 2021-05-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0004_auto_20210517_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl',
            name='image',
            field=models.ImageField(default=None, upload_to='mdls/img', verbose_name='Изображение модели'),
        ),
    ]
