# Generated by Django 3.2.3 on 2021-05-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0005_alter_mdl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl',
            name='tags',
            field=models.ManyToManyField(related_name='model_tags', to='mdls.Tag', verbose_name='Категории модели'),
        ),
    ]
