# Generated by Django 3.2.3 on 2021-05-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0006_alter_mdl_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdl',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
    ]
