# Generated by Django 3.2.3 on 2021-05-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
        ('mdls', '0008_mdl_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='accounts.userprofile', verbose_name='Автор'),
        ),
    ]
