# Generated by Django 3.2.3 on 2021-05-17 00:40

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mdl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(auto_created=True, default='.fbx', max_length=10, verbose_name='Расширение модели')),
                ('name', models.CharField(max_length=50, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Описание модели')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('file', models.FileField(upload_to=pathlib.PureWindowsPath('E:/Работа для Коловрата/KolymaStore/src/mdls_files'), verbose_name='Файл модели')),
                ('tags', models.ManyToManyField(to='mdls.Tag', verbose_name='Категории модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['date', 'name'],
            },
        ),
    ]
