# Generated by Django 3.2.3 on 2021-05-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
        ('mdls', '0007_alter_mdl_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdl',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='accounts.userprofile', verbose_name='Автор'),
        ),
    ]
