# Generated by Django 3.2.3 on 2021-05-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(default=None, max_length=12, verbose_name='Номер телефона'),
        ),
    ]
