# Generated by Django 3.2.3 on 2021-05-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='accounts/img', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.TextField(default=None, max_length=12, verbose_name='Номер телефона'),
        ),
    ]
