# Generated by Django 3.2.3 on 2021-05-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default='2021-05-30', verbose_name='Срок выполнения'),
        ),
    ]
